### ISSUE TITLE
Project Schedule

### ISSUE THREAD

**Issue by TheGupta2012** [TheGupta2012/Quantum-Arrays#1]
# Project Timeline
This issue deals with the timeline for the project and the tasks associated in different phases of the project.

### PHASE 1 | Done
Literature review for the understanding of the algorithm. 
- [x] Understand each stage of the HighDist algorithm 
- [x] Generate QRAM for the A matrix
- [x] Read about QAE and QAA
- [ ] Read about fixed point AA
- OPTIONAL
- [ ] Read about Qauntum Amplitude Encoding for encoding distributions

#### Week 1
Optimization is done for the algorithm
- [x] Cached R1 and R2 registers for a very large decrease in depth
- [x] Optimize HDq and CMP - cached the ancilla across ALL operations
- [ ] ~~Find a way to do CondMAJ without width wise copies~~
- [x] Try to find an implementation of QAE which will fit the algorithm - going forward with basic QAE as other are measurement based ( will need to look further though )
- [x] See if register Rfi can be removed - YES, in min-entropy and k-distinctness
- [ ] ~~See if amplification of Rfo can be done independently~~

#### Week 2
The class structures of the HighDist algo is defined keeping in mind the python module formats
- [x] Define the class structure for HighDist algo - defined tree, dependencies and methods
- [x] Define class params 
- [x] Define CMP, HDq, Maj methods
- [x] Define QAE routine - using the basic qpe based approach for now
- [x] Define QAA routine
- [ ] ~~Define quantum params - backend type, shots, key of user, etc.~~ ( here, we are constrained with simulators as of now )
#### Week 3
The class structure of Pmax is defined
- [x] Define the class structure for the Pmax algo
- [x] Define parameters of algo
- [x] Link with HighDist 
- [x] Define F(inf) class
- [ ] Define GKD class
- [ ] Define Min Entropy class
        

#### Week1 
- [x] Code the EQ, HDq and CMP routines
- [x] Code the CondMAJ 
- [x] Code A matrix
- [x] Code Q matrix
#### Week2 
- [x] QAE routine
- [x] Read about QAA 
- [x] Implement QAA
#### Week3 
- [x] Implement HighDist till stage 3
- [x] Implement stage 4
- [x] Implement QAA in HighDist
#### Week4 
- [x] add support for the transpiler optimization during parameter updation
- [x] Implement the Pmax algo
- [x] Define the Finf class
- [ ] Define the GKD and KD classes

#### Week5
- [ ] Define the job delegation for the mps-simulator in IBMQ 

### PHASE 4
to-do
